version: 2
updates:
  - package-ecosystem: pip
    directory: /app/backend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /app/frontend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /app/backend
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /app/frontend
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
